name: site-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: "https://cities.bieda.it/"
        allow_issue_writing: true
        artifact_name: "zap-report"
        cmd_options: "-a -J zap-report.json -w zap-report.html"
    - name: Copy ZAP Report from container to workspace
      run: |
        cp /zap/wrk/zap-report.html .
        cp /zap/wrk/zap-report.json .
    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html