name: site-security-scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: "https://cities.bieda.it/"
        allow_issue_writing: true